DefaultContentLanguage: en
MetaDataFormat: yaml
buildFuture: true
baseURL: 'https://www.thenewdynamic.com'
enableRobotsTXT: true
googleAnalytics: ''
languageCode: en-us
themesDir: components
theme:
  - hugo-layout_module-base-2019
preserveTaxonomyNames: true
disableAliases: true
blackfriday:
  extensionsmask:
    - noIntraEmphasis
mediaTypes:
  text/netlify:
    delimiter: ''
    suffixes:
      - ''
outputFormats:
  HEADERS:
    baseName: _headers
    isPlainText: true
    mediatype: text/netlify
    notAlternative: true
  REDIR:
    baseName: _redirects
    isPlainText: true
    mediatype: text/netlify
    notAlternative: true
outputs:
  home:
    - HTML
    - HEADERS
    - REDIR
sitemap:
  changefreq: monthly
  filename: sitemap.xml
  priority: 0.5
social: {}
taxonomies:
  tag: tags

